# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_fr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fr', models.CharField(max_length=200)),
                ('iso', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('description_fr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_fr', models.CharField(max_length=200)),
                ('year_inscribed', models.IntegerField(default=0)),
                ('endangered', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('long_description', models.TextField(default='')),
                ('long_description_fr', models.TextField(default='')),
                ('short_description', models.TextField(default='')),
                ('short_description_fr', models.TextField(default='')),
                ('justification', models.TextField(default='')),
                ('justification_fr', models.TextField(default='')),
                ('historical_description', models.TextField(default='')),
                ('historical_description_fr', models.TextField(default='')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Criterion')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_fr', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Zone'),
        ),
    ]
