# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='id',
        ),
        migrations.AlterField(
            model_name='criterion',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
