# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170914_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='thumb',
            field=models.BinaryField(default=b''),
        ),
    ]
