# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170910_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='site',
            name='country',
        ),
        migrations.AddField(
            model_name='site',
            name='country',
            field=models.ManyToManyField(to='app.Country'),
        ),
        migrations.RemoveField(
            model_name='site',
            name='criteria',
        ),
        migrations.AddField(
            model_name='site',
            name='criteria',
            field=models.ManyToManyField(to='app.Criterion'),
        ),
    ]
