# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170910_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='zone',
        ),
        migrations.AddField(
            model_name='site',
            name='zosne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Zone'),
        ),
        migrations.AlterField(
            model_name='site',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='app.Country'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
