# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170914_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
