# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170910_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='zosne',
            new_name='zone',
        ),
    ]
