# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170910_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='country',
            field=models.ManyToManyField(to='app.Country'),
        ),
    ]
