# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_site_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
