# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170916_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='site',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='site',
            name='seen',
        ),
        migrations.AddField(
            model_name='user',
            name='disliked_sites',
            field=models.ManyToManyField(related_name='disliked', to='app.Site'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_sites',
            field=models.ManyToManyField(related_name='liked', to='app.Site'),
        ),
        migrations.AddField(
            model_name='user',
            name='seen_sites',
            field=models.ManyToManyField(related_name='seen', to='app.Site'),
        ),
    ]
