# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170918_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='searchable_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='searchable_name_fr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='searchable_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='searchable_name_fr',
            field=models.CharField(default='', max_length=200),
        ),
    ]
